language: node_js
dist: xenial
node_js:
  - "12"
cache:
  yarn: true

addons:
  chrome: stable

branches:
  only:
    - master
    - /^v\d+\.\d+(\.\d+)?(-\S*)?$/

# upgrade yarn to a more recent version
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.13.0
  - export PATH="$HOME/.yarn/bin:$PATH"

jobs:
  include:
    - name: "Build & Deploy"
      script: |
        set -ex
        yarn run build
        yarn run build-examples
        yarn run build-tests
        yarn run test
      deploy:
        - provider: script
          script: ./scripts/publish-packages.sh
          skip_cleanup: true
          on:
            tags: true
            branch: master
        - provider: pages
          skip_cleanup: true
          commiter-from-gh: true
          keep-history: false
          local-dir: examples
          github-token: $GITHUB_TOKEN
          on:
            tags: true
            branch: master

